### ISSUE TITLE
如何支持实时录音

### ISSUE THREAD

**Issue by KingQianBei** [Cesaradu/AudioSpectrumDemo#4]
如题，作者你好，我最近在做实时语音的功能，找了好多天音频频谱都没有发现好的，你的算是找到的里面比较好的了，但是运行demo看都是根据本地音频文件展示频谱的，我要根据录音实时展示请问怎么做呢？

**Comment by Cesaradu** [comment]
你好，demo里目前有播放本地音频和录音两种可选，你看看是否满足你的需求

**Comment by KingQianBei** [comment]
可以支持实时录音的么？请问是1还是2里面的可以单独抽取到我的项目里面来用么？

**Comment by Cesaradu** [comment]
> 可以支持实时录音的么？请问是1还是2里面的可以单独抽取到我的项目里面来用么？

支持录音的，你选择录音进去就行了

**Comment by KingQianBei** [comment]
好的，谢谢，我今天尝试一下，如果有问题再向你请教

**Comment by KingQianBei** [comment]
你好，前两天用在实时语音识别的那里是可以了，现在增加一个录音机功能，用的是AVAudioRecorder，这个没有像之前那个的实时的回调，也没有传给RealtimeAnalyzer里面的buffer，这个请问怎么处理啊，我可以在启动录音的时候用一个定时器0.1秒去更新，但是没有buffer这个参数传

**Comment by Cesaradu** [comment]
> 你好，前两天用在实时语音识别的那里是可以了，现在增加一个录音机功能，用的是AVAudioRecorder，这个没有像之前那个的实时的回调，也没有传给RealtimeAnalyzer里面的buffer，这个请问怎么处理啊，我可以在启动录音的时候用一个定时器0.1秒去更新，但是没有buffer这个参数传

录音器就用demo的录音一样实现就好了，不要用AVAudioRecorder

**Comment by KingQianBei** [comment]
好的谢谢
